### ISSUE TITLE
腾讯云函数执行失败

### ISSUE THREAD

**Issue by ycmade** [fakedon/checkin#11]
返回数据:

{"errorCode":-1,"errorMessage":"Traceback (most recent call last):\n  File \"/var/runtime/python3/bootstrap.py\", line 133, in init_handler\n    func_handler = get_func_handler(file.rsplit(\".\", 1)[0], func)\n  File \"/var/runtime/python3/bootstrap.py\", line 159, in get_func_handler\n    mod = imp.load_module(mname, *imp.find_module(mname))\n  File \"/var/lang/python3/lib/python3.6/imp.py\", line 234, in load_module\n    return load_source(name, filename, file)\n  File \"/var/lang/python3/lib/python3.6/imp.py\", line 172, in load_source\n    module = _load(spec)\n  File \"\u003cfrozen importlib._bootstrap\u003e\", line 675, in _load\n  File \"\u003cfrozen importlib._bootstrap\u003e\", line 655, in _load_unlocked\n  File \"\u003cfrozen importlib._bootstrap_external\u003e\", line 678, in exec_module\n  File \"\u003cfrozen importlib._bootstrap\u003e\", line 205, in _call_with_frames_removed\n  File \"/var/user/index.py\", line 18, in \u003cmodule\u003e\n    from croniter import croniter, croniter_range\nModuleNotFoundError: No module named 'croniter'"}

日志:

START RequestId: 70ba4145-3998-469e-b33f-1d168dac76fd

Event RequestId: 70ba4145-3998-469e-b33f-1d168dac76fd

 

ERROR RequestId:70ba4145-3998-469e-b33f-1d168dac76fd Result:{"errorCode":-1,"errorMessage":"Traceback (most recent call last):\n  File \"/var/runtime/python3/bootstrap.py\", line 133, in init_handler\n    func_handler = get_func_handler(file.rsplit(\".\", 1)[0], func)\n  File \"/var/runtime/python3/bootstrap.py\", line 159, in get_func_handler\n    mod = imp.load_module(mname, *imp.find_module(mname))\n  File \"/var/lang/python3/lib/python3.6/imp.py\", line 234, in load_module\n    return load_source(name, filename, file)\n  File \"/var/lang/python3/lib/python3.6/imp.py\", line 172, in load_source\n    module = _load(spec)\n  File \"\u003cfrozen importlib._bootstrap\u003e\", line 675, in _load\n  File \"\u003cfrozen importlib._bootstrap\u003e\", line 655, in _load_unlocked\n  File \"\u003cfrozen importlib._bootstrap_external\u003e\", line 678, in exec_module\n  File \"\u003cfrozen importlib._bootstrap\u003e\", line 205, in _call_with_frames_removed\n  File \"/var/user/index.py\", line 18, in \u003cmodule\u003e\n    from croniter import croniter, croniter_range\nModuleNotFoundError: No module named 'croniter'"} 

END RequestId: 70ba4145-3998-469e-b33f-1d168dac76fd

Report RequestId: 70ba4145-3998-469e-b33f-1d168dac76fd Duration:0ms Memory:128MB MemUsage:0.000000MB

**Comment by ycmade** [comment]
现在用github actions搞定了，能不能完成之后加一个通知呢，server酱就很不错

**Comment by fakedon** [comment]
只能有空整下，本来我也没渴求每天都能签到成功..
