### ISSUE TITLE
云函数 显示*号

### ISSUE THREAD

**Issue by Silentely** [fakedon/checkin#7]
![](https://ftp.bmp.ovh/imgs/2020/07/d21277dfa678e338.png)

显示*号
且金钱并未增加。

**Comment by fakedon** [comment]
我刚改成显示星号，毕竟github actions任何人都可以查看，有泄露账号风险
如果你要显示内容，修改19行show_log = False改为show_log = True即可
没增加你查看下https://www.hostloc.com/home.php?mod=spacecp&ac=credit&op=log&suboperation=creditrulelog
看看最后奖励时间，最可能的情况就是脚本今天已经运行过了，新版脚本再次运行就不增加金钱了

**Comment by Silentely** [comment]
> 我刚改成显示星号，github上的动作任何人都可以查看，有引发账号风险
> 如果你要显示内容，修改19行show_log = False替换show_log = True就没
> 增加你查看下[https：// www .hostloc.com / home.php？mod = spacecp＆ac = credit＆op = log＆suboperation = creditrulelog](https://www.hostloc.com/home.php?mod=spacecp&ac=credit&op=log&suboperation=creditrulelog)
> 看看最后奖励时间，最可能的情况就是脚本今天已经过了，新版本脚本再次运行就不增加金钱了

好的 谢谢，因为我查看日志40分显示调用成功，但是日志记录显示错误。后面再次运行超时。目前已解决 谢谢了

**Comment by fakedon** [comment]
我刚修改了下脚本，云函数默认显示访问id，github actions默认不显示
你只需重新复制脚本，不需要再修改

**Comment by Silentely** [comment]
> 我刚修改了下脚本，云函数默认显示访问id，github actions默认不显示
> 你只需重新复制脚本，不需要再修改

好的 已经修改 非常感谢
